<?php
/**
 * wp-admin → openclaWP → Tasks page.
 *
 * Read-only DataViews surface for Action Scheduler queue entries scoped to
 * agents-related groups. v0 lists pending / running / complete / failed
 * actions filtered to the `agents-api` group (where the workflow bridge
 * registers cron triggers); the surface is intentionally generic so future
 * non-workflow background jobs (queued tool calls, deferred webhooks)
 * surface here too once we expose an enqueue path.
 *
 * The renderer is just a mount root — `assets/tasks-admin.js` (built from
 * `blocks/chat/src/tasks.js` via wp-scripts) hydrates the DataView.
 *
 * @package OpenclaWP
 * @since   0.5.0
 */

defined( 'ABSPATH' ) || exit;

final class OpenclaWP_Tasks_Admin {

	public const PAGE_SLUG = 'openclawp-tasks';

	public static function register(): void {
		add_action( 'admin_menu', array( __CLASS__, 'register_submenu' ), 17 );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_assets' ) );
	}

	public static function register_submenu(): void {
		add_submenu_page(
			OpenclaWP_Admin::PAGE_SLUG,
			__( 'Tasks', 'openclawp' ),
			__( 'Tasks', 'openclawp' ),
			'manage_options',
			self::PAGE_SLUG,
			array( __CLASS__, 'render_page' )
		);
	}

	public static function enqueue_assets( $hook ): void {
		if ( self::hook_suffix() !== $hook ) {
			return;
		}

		$build_url  = plugins_url( 'blocks/tasks/build/', OPENCLAWP_PLUGIN_FILE );
		$build_path = OPENCLAWP_PATH . 'blocks/tasks/build/';
		$asset_file = $build_path . 'view.asset.php';

		// `view.asset.php` is generated by wp-scripts; without it WP can't
		// resolve our externalised React/components handles. Fail loud in
		// debug so we never half-render the page silently.
		if ( ! file_exists( $asset_file ) ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				wp_die( esc_html__( 'openclaWP Tasks: missing build artefacts. Run `npm run build` in the plugin directory.', 'openclawp' ) );
			}
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_script(
			'openclawp-tasks-admin',
			$build_url . 'view.js',
			array_unique(
				array_merge(
					array( 'wp-api-fetch' ),
					(array) ( $asset['dependencies'] ?? array() )
				)
			),
			(string) ( $asset['version'] ?? OPENCLAWP_VERSION ),
			true
		);

		// `@wordpress/dataviews` is bundled into our view.js (wp-scripts
		// doesn't externalise it on WP 7.0). The matching CSS is copied
		// out of `node_modules/@wordpress/dataviews/build-style/style.css`
		// at build time (see `npm run build:tasks`) and lives next to
		// view.js. Enqueue it here so the table chrome / icons render.
		wp_enqueue_style(
			'openclawp-tasks-admin',
			$build_url . 'view.css',
			array( 'wp-components' ),
			(string) ( $asset['version'] ?? OPENCLAWP_VERSION )
		);

		wp_localize_script(
			'openclawp-tasks-admin',
			'openclaWPTasks',
			array(
				'restNamespace' => 'openclawp/v1',
				'nonce'         => wp_create_nonce( 'wp_rest' ),
				'tasksUrl'      => esc_url_raw( rest_url( 'openclawp/v1/tasks' ) ),
				'pollInterval'  => 5000,
			)
		);
	}

	public static function render_page(): void {
		?>
		<div class="wrap openclawp-tasks">
			<h1 class="wp-heading-inline"><?php esc_html_e( 'Tasks', 'openclawp' ); ?></h1>
			<hr class="wp-header-end" />

			<p class="description">
				<?php
				echo wp_kses(
					__(
						'Background work scheduled by openclaWP and the agents-api substrate. Cron-triggered workflows, deferred jobs, and any other action queued under the <code>agents-api</code> or <code>openclawp</code> Action Scheduler groups appear here.',
						'openclawp'
					),
					array( 'code' => array() )
				);
				?>
			</p>

			<div id="openclawp-tasks-root">
				<p><?php esc_html_e( 'Loading tasks…', 'openclawp' ); ?></p>
			</div>
		</div>
		<?php
	}

	private static function hook_suffix(): string {
		return 'openclawp_page_' . self::PAGE_SLUG;
	}
}
